name: Integration Tests & Unit Tests

on:
  push:
    branches:
      - '**'        # Any branch.
    tags:
      - '!*'        # Exclude tags.

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout branch: ${{ github.REF }}.'
        uses: actions/checkout@v2
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting.
          fetch-depth: 0
          ref: ${{ github.HEAD_REF }}
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 16
          java-package: jdk
      - uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: '${{ runner.os }}-gradle-${{ hashFiles(''.gradle/**'') }}'
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Run tests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./gradlew --no-daemon --stacktrace check
